### ISSUE TITLE
Not a bug: Porting Habari Hyde to WP ..

### ISSUE THREAD

**Issue by ginsterbusch** [miklb/Habari_Hyde#17]
hi there, 

just wanted to jot down, that I'm currently porting Habari Hyde to WP, incorporating the latest Jekyll Hyde CSS code. Right now I'm done with the groundwork, and starting to work on the usual functions.php stuff (thou I'm a OOP man, adding the latest fun in OOP Parent vs. Child Theme technoledge).

**Comment by miklb** [comment]
I don’t mess with WP anymore, but good luck. I’ve looked at the latest code, and am holding off on using the REM for the columns. Seems a little buggy at smaller device widths.

**Comment by ginsterbusch** [comment]
Interesting fact: Right now I'm porting Habari Hyde to my own "data storage-agnostic" CMS / toolkit :-D
