### ISSUE TITLE
use SSL for links to resources that support them

### ISSUE THREAD

**Issue by skpy** [miklb/Habari_Hyde#20]
If I enable SSL on my website using Hyde as my theme, I get browser complaints that non-secure items are being served.  Looking through the source, it appears that the offending element is the Google fonts, added in theme.php:

``` php
Stack::add('template_stylesheet', 'http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,400italic|Abril+Fatface', 'fonts' );
```

If you change that http to https, my site no longer raises the error when running under SSL.

I'd suggest using HTTPS for everything, by default; but I'd accept a conditional check in that Stack call to use whatever http scheme the current request is using.

**Comment by miklb** [comment]
I _think_ if I leave out the http: all together, it will load the fonts and not interfere with the https. I haven't had much time to hack on any of my stuff, but am in need to work on another personal project and will look into everything soon. Thanks for the feedback!

**Comment by miklb** [comment]
I think SHA: 8f24c2ea353afbb93539d64d81dec95e4f245aaf fixes this issue. Can you confirm?

**Comment by skpy** [comment]
Confirmed. This works as desired.
